// src/utils/routesData.js
export const routeData = [
  { start: "Lagos", end: "Ibadan" },
  { start: "Lagos", end: "Abeokuta" },
  { start: "Abeokuta", end: "Ijebu Ode" },
  { start: "Abeokuta", end: "Sagamu" },
  { start: "Ijebu Ode", end: "Shagamu" },
  { start: "Lagos", end: "Ado Ekiti" },
  { start: "Lagos", end: "Akure" },
  { start: "Lagos", end: "Benin City" },
  { start: "Abuja", end: "Minna" },
  { start: "Abuja", end: "Lokoja" },
  { start: "Abuja", end: "Kano" },
  { start: "Abuja", end: "Jos" },
  { start: "Kano", end: "Kaduna" },
  { start: "Kano", end: "Zaria" },
  { start: "Kaduna", end: "Sokoto" },
  { start: "Port Harcourt", end: "Uyo" },
  { start: "Port Harcourt", end: "Enugu" },
  { start: "Enugu", end: "Awka" },
  { start: "Enugu", end: "Nsukka" },
  { start: "Jos", end: "Makurdi" },
  { start: "Makurdi", end: "Lafia" },
  { start: "Lagos", end: "Oshogbo" },
  { start: "Oshogbo", end: "Ado Ekiti" },
  { start: "Ibadan", end: "Ogbomosho" },
  { start: "Ogbomosho", end: "Ilorin" },
  { start: "Ilorin", end: "Offa" },
  { start: "Lokoja", end: "Auchi" },
  { start: "Auchi", end: "Benin City" },
  { start: "Benin City", end: "Warri" },
  { start: "Warri", end: "Asaba" },
  { start: "Asaba", end: "Onitsha" },
  { start: "Onitsha", end: "Owerri" },
  { start: "Owerri", end: "Aba" },
  { start: "Aba", end: "Calabar" },
  { start: "Calabar", end: "Uyo" },
  { start: "Uyo", end: "Ikot Ekpene" },
  { start: "Ikot Ekpene", end: "Abakaliki" },
  { start: "Abakaliki", end: "Nsukka" },
  { start: "Nsukka", end: "Otukpo" },
  { start: "Otukpo", end: "Makurdi" },
  { start: "Makurdi", end: "Gboko" },
  { start: "Gboko", end: "Katsina-Ala" },
  { start: "Katsina-Ala", end: "Jalingo" },
  { start: "Jalingo", end: "Yola" },
  { start: "Yola", end: "Mubi" },
  { start: "Mubi", end: "Maiduguri" },
  { start: "Maiduguri", end: "Damaturu" },
  { start: "Damaturu", end: "Gombe" },
  { start: "Gombe", end: "Bauchi" },
  { start: "Bauchi", end: "Jos" },
  { start: "Jos", end: "Abuja" },
   { start: "Lagos", end: "Ibadan" },
  { start: "Lagos", end: "Abuja" },
  { start: "Lagos", end: "Kano" },
  { start: "Lagos", end: "Port Harcourt" },
  { start: "Lagos", end: "Enugu" },
  { start: "Lagos", end: "Benin City" },
  { start: "Lagos", end: "Ilorin" },
  { start: "Lagos", end: "Abeokuta" },
  { start: "Lagos", end: "Calabar" },
  { start: "Lagos", end: "Owerri" },
  { start: "Lagos", end: "Onitsha" },
  { start: "Lagos", end: "Makurdi" },
  { start: "Lagos", end: "Lokoja" },
  { start: "Abuja", end: "Kaduna" },
  { start: "Abuja", end: "Jos" },
  { start: "Abuja", end: "Bauchi" },
  { start: "Abuja", end: "Minna" },
  { start: "Abuja", end: "Keffi" },
  { start: "Abuja", end: "Lokoja" },
  { start: "Abuja", end: "Gombe" },
  { start: "Ibadan", end: "Ilorin" },
  { start: "Ibadan", end: "Abeokuta" },
  { start: "Ibadan", end: "Osogbo" },
  { start: "Ibadan", end: "Akure" },
  { start: "Kano", end: "Katsina" },
  { start: "Kano", end: "Sokoto" },
  { start: "Kano", end: "Maiduguri" },
  { start: "Kano", end: "Gombe" },
  { start: "Kano", end: "Damaturu" },
  { start: "Kano", end: "Bauchi" },
  { start: "Port Harcourt", end: "Owerri" },
  { start: "Port Harcourt", end: "Uyo" },
  { start: "Port Harcourt", end: "Aba" },
  { start: "Port Harcourt", end: "Calabar" },
  { start: "Port Harcourt", end: "Enugu" },
  { start: "Benin City", end: "Asaba" },
  { start: "Benin City", end: "Warri" },
  { start: "Benin City", end: "Sapele" },
  { start: "Benin City", end: "Onitsha" },
  { start: "Benin City", end: "Lokoja" },
  { start: "Enugu", end: "Awka" },
  { start: "Enugu", end: "Nsukka" },
  { start: "Enugu", end: "Abakaliki" },
  { start: "Enugu", end: "Makurdi" },
  { start: "Enugu", end: "Onitsha" },
  { start: "Jos", end: "Bauchi" },
  { start: "Jos", end: "Gombe" },
  { start: "Jos", end: "Makurdi" },
  { start: "Jos", end: "Kaduna" },
  { start: "Ilorin", end: "Lokoja" },
  { start: "Ilorin", end: "Offa" },
  { start: "Ilorin", end: "Jebba" },
  { start: "Ilorin", end: "Minna" },
  { start: "Ilorin", end: "Ado Ekiti" },
  { start: "Abeokuta", end: "Ijebu Ode" },
  { start: "Abeokuta", end: "Sango Ota" },
  { start: "Abeokuta", end: "Ilaro" },
  { start: "Abeokuta", end: "Ibadan" },
  { start: "Owerri", end: "Aba" },
  { start: "Owerri", end: "Umuahia" },
  { start: "Owerri", end: "Nsukka" },
  { start: "Owerri", end: "Asaba" },
  { start: "Calabar", end: "Uyo" },
  { start: "Calabar", end: "Ikom" },
  { start: "Calabar", end: "Abakaliki" },
  { start: "Calabar", end: "Enugu" },
  { start: "Makurdi", end: "Lafia" },
  { start: "Makurdi", end: "Otukpo" },
  { start: "Makurdi", end: "Gboko" },
  { start: "Makurdi", end: "Jos" },
  { start: "Yola", end: "Mubi" },
  { start: "Yola", end: "Jalingo" },
  { start: "Yola", end: "Gombe" },
  { start: "Sokoto", end: "Kebbi" },
  { start: "Sokoto", end: "Gusau" },
  { start: "Sokoto", end: "Kano" },
  { start: "Sokoto", end: "Birnin Kebbi" },
  { start: "Maiduguri", end: "Damaturu" },
  { start: "Maiduguri", end: "Potiskum" },
  { start: "Maiduguri", end: "Bama" },
  { start: "Maiduguri", end: "Gombe" },
  { start: "Ado Ekiti", end: "Akure" },
  { start: "Ado Ekiti", end: "Ibadan" },
  { start: "Ado Ekiti", end: "Ilorin" },
  { start: "Akure", end: "Osogbo" },
  { start: "Akure", end: "Ondo Town" },
  { start: "Akure", end: "Ibadan" },
  { start: "Osogbo", end: "Ilesa" },
  { start: "Osogbo", end: "Ogbomoso" },
  { start: "Osogbo", end: "Ibadan" },
  { start: "Katsina", end: "Daura" },
  { start: "Katsina", end: "Zaria" },
  { start: "Zaria", end: "Kaduna" },
  { start: "Zaria", end: "Bauchi" },
  { start: "Kano", end: "Zaria" },
  { start: "Gombe", end: "Bauchi" },
  { start: "Gombe", end: "Yola" },
  { start: "Gombe", end: "Damaturu" },
  { start: "Damaturu", end: "Potiskum" },
  { start: "Keffi", end: "Lafia" },
  { start: "Keffi", end: "Abuja" },
  { start: "Lokoja", end: "Okene" },
  { start: "Lokoja", end: "Kabba" },
];
